# Generated by Django 3.1.3 on 2021-08-26 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0004_auto_20210826_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='auther',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='auther',
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.question'),
        ),
    ]
